### ISSUE TITLE
Fail to startup 1.2

### ISSUE THREAD

**Issue by Telem** [faljse/SDNotify#4]
Hello,

Unfortunately, it seems like 1.2 won't start for us. Here is the relevant piece of stacktrace :
```
Caused by: java.lang.Error: Structure.getFieldOrder() on class info.faljse.SDNotify.jna.CLibrary$SockAddr returns names ([addr, family]) which do not match declared field names ([addr])
at com.sun.jna.Structure.getFields(Structure.java:1027)
at com.sun.jna.Structure.deriveLayout(Structure.java:1172)
at com.sun.jna.Structure.calculateSize(Structure.java:1097)
at com.sun.jna.Structure.calculateSize(Structure.java:1049)
at com.sun.jna.Structure.allocateMemory(Structure.java:403)
at com.sun.jna.Structure.<init>(Structure.java:194)
at com.sun.jna.Structure.<init>(Structure.java:182)
at com.sun.jna.Structure.<init>(Structure.java:169)
at com.sun.jna.Structure.<init>(Structure.java:161)
at info.faljse.SDNotify.jna.CLibrary$SockAddr.<init>(CLibrary.java:70)
at info.faljse.SDNotify.SDNotify.<init>(SDNotify.java:46)
at info.faljse.SDNotify.SDNotify.getInstance(SDNotify.java:184)
at info.faljse.SDNotify.SDNotify.isAvailable(SDNotify.java:59)
...
```

If that's any help : the OS is CentOS Linux release 7.5.1804, kernel is 3.10.0-862.11.6.el7.x86_64.

Cheers

**Comment by faljse** [comment]
Stupid me :)
Just released version 1.3 on sonatype
